// app/dashboard/dashboard.tsx
"use client"

import { useState } from "react"
import Image from "next/image"
import { useRouter } from "next/navigation"
import PageTransition from "../components/page-transition"
import {
  Monitor,
  Users,
  Mic2,
  FileText,
  BarChart3,
  KeyRound,
  ChevronDown,
  TrendingUp,
  TrendingDown,
  FileIcon,
  Menu,
  X,
} from "lucide-react"

export default function Dashboard() {
  const [dateRange, setDateRange] = useState("1 de Mar de 2023 a 9 de Mar de 2023")
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false)
  const router = useRouter()

  const handleNavigation = (path: string) => {
    router.push(path)
    setMobileMenuOpen(false)
  }

  return (
    <PageTransition>
      <div className="flex flex-col h-screen">
        {/* Header */}
        <header className="bg-black text-white py-3 px-4 md:px-6 flex justify-between items-center">
          <div className="flex items-center gap-2 md:gap-3">
            <div className="w-8 h-8 md:w-12 md:h-12 bg-gray-300 rounded-full"></div>
            <div>
              <h1 className="text-sm md:text-base font-medium">Nome do projeto</h1>
              <p className="text-[10px] md:text-xs text-gray-400">DESCRIÇÃO COMPLETA</p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <div className="md:flex items-center gap-3 hidden">
              <div className="w-9 h-9 bg-gray-300 rounded-full overflow-hidden">
                {/* Espaço vazio para foto do usuário */}
              </div>
              <div>
                <p className="text-xs text-gray-400">Seja bem vindo!</p>
                <p className="text-sm">Nome do usuário</p>
              </div>
            </div>
            <ChevronDown size={16} className="hidden md:block" />
            <button className="md:hidden text-white" onClick={() => setMobileMenuOpen(!mobileMenuOpen)}>
              {mobileMenuOpen ? <X size={24} /> : <Menu size={24} />}
            </button>
          </div>
        </header>

        <div className="flex flex-1 relative">
          {/* Mobile Menu Overlay */}
          {mobileMenuOpen && (
            <div
              className="fixed inset-0 bg-black bg-opacity-50 z-20 md:hidden"
              onClick={() => setMobileMenuOpen(false)}
            ></div>
          )}

          {/* Sidebar */}
          <aside
            className={`${
              mobileMenuOpen ? "translate-x-0" : "-translate-x-full"
            } fixed top-[57px] bottom-0 w-[200px] bg-gray-100 z-30 transition-transform duration-300 ease-in-out md:translate-x-0 md:static md:z-0`}
          >
            <nav>
              <ul>
                <li>
                  <button
                    className="flex items-center gap-3 py-4 px-6 bg-[#B8860B] text-white font-medium hover:bg-[#a67719] transition-colors w-full text-left"
                    onClick={() => handleNavigation("/dashboard")}
                  >
                    <Monitor size={20} />
                    DASHBOARD
                  </button>
                </li>
                <li>
                  <button
                    className="flex items-center gap-3 py-4 px-6 text-gray-700 font-medium hover:bg-[#B8860B] hover:text-white transition-colors w-full text-left"
                    onClick={() => handleNavigation("/users")}
                  >
                    <Users size={20} />
                    USUÁRIOS
                  </button>
                </li>
                <li>
                  <button
                    className="flex items-center gap-3 py-4 px-6 text-gray-700 font-medium hover:bg-[#B8860B] hover:text-white transition-colors w-full text-left"
                    onClick={() => handleNavigation("/musicians")}
                  >
                    <Mic2 size={20} />
                    MÚSICOS
                  </button>
                </li>
                <li>
                  <button
                    className="flex items-center gap-3 py-4 px-6 text-gray-700 font-medium hover:bg-[#B8860B] hover:text-white transition-colors w-full text-left"
                    onClick={() => setMobileMenuOpen(false)}
                  >
                    <FileText size={20} />
                    SOLICITAÇÕES
                  </button>
                </li>
                <li>
                  <button
                    className="flex items-center gap-3 py-4 px-6 text-gray-700 font-medium hover:bg-[#B8860B] hover:text-white transition-colors w-full text-left"
                    onClick={() => setMobileMenuOpen(false)}
                  >
                    <BarChart3 size={20} />
                    FINANCEIRO
                  </button>
                </li>
                <li>
                  <button
                    className="flex items-center gap-3 py-4 px-6 text-gray-700 font-medium hover:bg-[#B8860B] hover:text-white transition-colors w-full text-left"
                    onClick={() => setMobileMenuOpen(false)}
                  >
                    <KeyRound size={20} />
                    ACESSOS
                  </button>
                </li>
              </ul>
            </nav>
          </aside>

          {/* Main Content */}
          <main className="flex-1 p-4 md:p-6 bg-white overflow-auto">
            {/* Date Range Selector */}
            <div className="flex justify-end mb-4 md:mb-6">
              <div className="relative">
                <button className="flex items-center gap-2 bg-gray-200 px-3 py-1.5 md:px-4 md:py-2 rounded text-xs md:text-sm">
                  {dateRange}
                  <ChevronDown size={16} />
                </button>
              </div>
            </div>

            {/* Stats Cards */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 md:gap-6 mb-4 md:mb-6">
              {/* Users Card */}
              <div className="bg-white rounded-lg shadow p-4 md:p-6 flex justify-between items-center">
                <div>
                  <h2 className="text-xl md:text-2xl font-bold">83.706</h2>
                  <p className="text-sm text-gray-500">Usuários</p>
                </div>
                <div className="flex flex-col items-end">
                  <span className="text-emerald-500 flex items-center text-xs md:text-sm gap-1">
                    <TrendingUp size={16} />
                    50,2%
                  </span>
                  <div className="w-10 h-10 md:w-12 md:h-12 bg-[#B8860B] rounded-full flex items-center justify-center mt-1">
                    <Users size={16} className="text-white" />
                  </div>
                </div>
              </div>

              {/* Musicians Card */}
              <div className="bg-white rounded-lg shadow p-4 md:p-6 flex justify-between items-center">
                <div>
                  <h2 className="text-xl md:text-2xl font-bold">022</h2>
                  <p className="text-sm text-gray-500">Músicos</p>
                </div>
                <div className="flex flex-col items-end">
                  <span className="text-red-500 flex items-center text-xs md:text-sm gap-1">
                    <TrendingDown size={16} />
                    50,2%
                  </span>
                  <div className="w-10 h-10 md:w-12 md:h-12 bg-black rounded-full flex items-center justify-center mt-1">
                    <Mic2 size={16} className="text-white" />
                  </div>
                </div>
              </div>

              {/* Financial Card */}
              <div className="bg-white rounded-lg shadow p-4 md:p-6 flex justify-between items-center">
                <div>
                  <h2 className="text-lg md:text-2xl font-bold">R$ 300000,00</h2>
                  <p className="text-sm text-gray-500">Total em caixa</p>
                </div>
                <div className="flex flex-col items-end">
                  <span className="text-red-500 flex items-center text-xs md:text-sm gap-1">
                    <TrendingDown size={16} />
                    50,2%
                  </span>
                  <div className="w-10 h-10 md:w-12 md:h-12 bg-teal-500 rounded-full flex items-center justify-center mt-1">
                    <BarChart3 size={16} className="text-white" />
                  </div>
                </div>
              </div>
            </div>

            {/* Charts and Lists */}
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 md:gap-6">
              {/* Chart - Apenas a imagem sem card */}
              <div className="lg:col-span-2">
                <div className="relative w-full" style={{ height: "400px" }}>
                  <Image
                    src="/images/usuarios-financeiro-chart.png"
                    alt="Gráfico Usuários x Financeiro"
                    fill
                    style={{ objectFit: "contain" }}
                    priority
                  />
                </div>
              </div>

              {/* Latest Requests */}
              <div className="bg-white rounded-lg shadow p-4 md:p-6">
                <div className="flex justify-between items-center mb-4 md:mb-6">
                  <h3 className="text-base md:text-lg font-medium">Últimas solicitações</h3>
                  <button className="text-[10px] md:text-xs text-gray-500 hover:underline">Mostrar todos</button>
                </div>

                <div className="space-y-3 md:space-y-4">
                  {Array.from({ length: 2 }).map((_, index) => (
                    <div key={index} className="p-3 md:p-4 border rounded-lg">
                      <div className="flex items-start gap-2 md:gap-3">
                        <FileIcon className="text-gray-500 mt-1" size={18} />
                        <div>
                          <p className="font-medium text-sm md:text-base">#01201200</p>
                          <p className="text-xs md:text-sm">Nome do músico</p>
                          <p className="text-[10px] md:text-xs text-gray-500">00/00/00</p>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </main>
        </div>
      </div>
    </PageTransition>
  )
}

// src/app/dashboard/dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
    selector: 'app-dashboard',
    templateUrl: './dashboard.component.html',
    styles: []
})
export class DashboardComponent implements OnInit {
    dateRange = '1 de Mar de 2023 a 9 de Mar de 2023';
    mobileMenuOpen = false;

    constructor(private router: Router) { }

    ngOnInit(): void {
        // Código de inicialização, se necessário
    }

    handleNavigation(path: string): void {
        this.router.navigate([path]);
        this.mobileMenuOpen = false;
    }
} 
<div class="p-6">
    <div class="flex justify-end mb-4">
        <button class="flex items-center gap-2 text-sm border border-gray-200 px-4 py-1.5 rounded">
            1 de Mar de 2023 a 9 de Mar de 2023
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none"
                stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="m6 9 6 6 6-6" />
            </svg>
        </button>
    </div>

    <!-- Stats Cards -->
    <div class="grid grid-cols-3 gap-6 mb-6">
        <!-- Users Card -->
        <div class="bg-white rounded-lg shadow p-4 flex justify-between items-center">
            <div>
                <h2 class="text-2xl font-bold">83.706</h2>
                <p class="text-sm text-gray-500">Usuários</p>
            </div>
            <div class="flex flex-col items-end">
                <span class="text-emerald-500 flex items-center text-sm gap-1">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none"
                        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                        <path d="m13 7 5 5-5 5" />
                        <path d="M6 7 V 17" />
                    </svg>
                    50,2%
                </span>
                <div class="w-12 h-12 bg-[#B8860B] rounded-full flex items-center justify-center mt-1">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                        stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                        <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path>
                        <circle cx="12" cy="7" r="4"></circle>
                    </svg>
                </div>
            </div>
        </div>

        <!-- Musicians Card -->
        <div class="bg-white rounded-lg shadow p-4 flex justify-between items-center">
            <div>
                <h2 class="text-2xl font-bold">022</h2>
                <p class="text-sm text-gray-500">Músicos</p>
            </div>
            <div class="flex flex-col items-end">
                <span class="text-red-500 flex items-center text-sm gap-1">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none"
                        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                        <path d="m13 17 5-5-5-5" />
                        <path d="M6 17 V 7" />
                    </svg>
                    50,2%
                </span>
                <div class="w-12 h-12 bg-black rounded-full flex items-center justify-center mt-1">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                        stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                        <path d="M9 18V5l12-2v13"></path>
                        <circle cx="6" cy="18" r="3"></circle>
                        <circle cx="18" cy="16" r="3"></circle>
                    </svg>
                </div>
            </div>
        </div>

        <!-- Financial Card -->
        <div class="bg-white rounded-lg shadow p-4 flex justify-between items-center">
            <div>
                <h2 class="text-2xl font-bold">R$ 300000,00</h2>
                <p class="text-sm text-gray-500">Total em caixa</p>
            </div>
            <div class="flex flex-col items-end">
                <span class="text-red-500 flex items-center text-sm gap-1">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none"
                        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                        <path d="m13 17 5-5-5-5" />
                        <path d="M6 17 V 7" />
                    </svg>
                    50,2%
                </span>
                <div class="w-12 h-12 bg-[#B8860B] rounded-full flex items-center justify-center mt-1">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                        stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                        <path d="M12 1v22M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"></path>
                    </svg>
                </div>
            </div>
        </div>
    </div>

    <!-- Main Chart -->
    <div class="bg-white rounded-lg shadow p-4 mb-6">
        <div class="flex justify-between items-center mb-4">
            <h3 class="font-medium">Usuários x Financeiro</h3>
        </div>
        <div class="p-4">
            <img src="assets/chart.png" alt="Gráfico de barras">
        </div>
    </div>

    <!-- Recent Requests -->
    <div class="bg-white rounded-lg shadow p-4">
        <div class="flex justify-between items-center mb-4">
            <h3 class="font-medium">Últimas solicitações</h3>
            <button class="text-[#B8860B] text-sm">Mostrar todas</button>
        </div>
        <div class="space-y-4">
            <div class="flex items-start gap-3">
                <div class="w-8 h-8 bg-gray-100 rounded-md flex items-center justify-center flex-shrink-0">
                    <span class="text-xs text-gray-600">#</span>
                </div>
                <div>
                    <p class="text-sm">#01201200</p>
                    <p class="text-xs text-gray-500">Nome do músico</p>
                    <p class="text-xs text-gray-500">00/00/00</p>
                </div>
            </div>
            <div class="flex items-start gap-3">
                <div class="w-8 h-8 bg-gray-100 rounded-md flex items-center justify-center flex-shrink-0">
                    <span class="text-xs text-gray-600">#</span>
                </div>
                <div>
                    <p class="text-sm">#01201200</p>
                    <p class="text-xs text-gray-500">Nome do músico</p>
                    <p class="text-xs text-gray-500">00/00/00</p>
                </div>
            </div>
        </div>
    </div>
</div>
